import argparse
import csv
import numpy as np
from sklearn.linear_model import LogisticRegression


def load_data(path):
    pairs = {}
    with open(path, newline="") as f:
        reader = csv.reader(f)
        for row in reader:
            length = int(row[0])
            width = int(row[1])
            jit = int(row[2])
            seconds = float(row[4])
            key = (length, width)
            entry = pairs.setdefault(key, {})
            entry["jit" if jit else "interp"] = seconds
    X, y = [], []
    for (length, width), t in pairs.items():
        if "jit" in t and "interp" in t:
            speedup = t["interp"] / t["jit"]
            X.append([length, width])
            y.append(1 if speedup > 1.0 else 0)
    return np.array(X), np.array(y)


def main():
    parser = argparse.ArgumentParser(description="Train JIT selector model")
    parser.add_argument("dataset", help="CSV generated by goof2")
    parser.add_argument("--out", default="tools/ml_jit_selector/model.dat",
                        help="Output model file")
    args = parser.parse_args()
    X, y = load_data(args.dataset)
    if len(X) == 0:
        raise SystemExit("Dataset lacks paired JIT and interpreter runs")
    clf = LogisticRegression().fit(X, y)
    coef = clf.coef_[0]
    with open(args.out, "w") as f:
        f.write(f"{coef[0]} {coef[1]} {clf.intercept_[0]}\n")


if __name__ == "__main__":
    main()
